name: app_flutter
description: App para fomentar el reciclaje electronico
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.27.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2 
  latlong2: ^0.9.1
  geolocator: ^13.0.2
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  carousel_slider: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets: 
    - assets/images/slash.png
    - assets/images/logo.png
    - assets/images/slider1.png
    - assets/images/slider2.png
    - assets/images/slider3.png
    - assets/images/slider4.png
    - assets/images/slider5.png
    - assets/db.json
    - assets/images/slash.png
    - assets/images/logo.png
    - assets/images/slider1.png
    - assets/images/slider2.png
    - assets/images/slider3.png
    - assets/images/slider4.png
    - assets/images/slider5.png
    - assets/db.json
    - assets/images/celular.png
    - assets/images/coffee.png
    - assets/images/computer.png
    - assets/images/desktop.png
    - assets/images/fridge.png
    - assets/images/lamp.png
    - assets/images/impresora.png
    - assets/images/microwave.png
    - assets/images/router.png
